trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  acrLoginServer: 'sejalgitopsacr2026.azurecr.io'
  imageRepository: 'gitops-demo-app'

steps:
- script: |
    echo "<h1>GitOps Demo App - Sejal Sakhala - Build $(Build.BuildId)</h1>" > index.html

    cat > Dockerfile <<EOF
    FROM nginx:latest
    COPY index.html /usr/share/nginx/html/index.html
    EOF

    echo "Files created:"
    ls -la
  displayName: 'Create Demo App Files'

- task: Docker@2
  displayName: 'Build and Push Docker Image to ACR'
  inputs:
    containerRegistry: 'acr-sejal-connection'
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    git config --global user.email "azuredevops@sejal.com"
    git config --global user.name "Azure DevOps Pipeline"

    echo "Cloning manifest repository..."
    git clone https://hedwig02:${GITHUBPAT}@github.com/hedwig02/aks-manifests-sejal.git manifest-repo

    cd manifest-repo

    echo "Files inside manifest repo:"
    ls -la

    echo "Updating deployment.yaml image..."
    sed -i "s|image: .*|image: $(acrLoginServer)/$(imageRepository):$(Build.BuildId)|" deployment.yaml

    echo "Updated deployment.yaml:"
    cat deployment.yaml

    git add deployment.yaml
    git commit -m "Update image tag to $(Build.BuildId)" || echo "No changes to commit"
    git push origin main
  displayName: 'Update Kubernetes Manifest Repo'
  env:
    GITHUBPAT: $(GITHUBPAT)